name: Python Tests  # 工作流名称

# 触发条件：推送到所有分支 / 对所有分支创建 PR 时触发
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境：Ubuntu 最新版
    strategy:
      fail-fast: false  # 一个版本失败不影响其他版本（可选）
      matrix:
        python-version: ["3.12"]  # 仅需匹配 Docker 中的 Python 3.12 版本

    steps:
    - uses: actions/checkout@v4  # 第一步：拉取当前仓库代码
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # 缓存 pip 依赖，加速后续运行
    
    - name: Install dependencies  # 安装依赖（基于 requirements.txt）
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test with pytest  # 运行 pytest 测试
      run: |
        pytest tests/test_app.py -v  # 明确指定测试文件，输出详细日志

